app = "ai-powered-scribing-app"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  # Increase timeout for long audio processing
  [[http_service.checks]]
    interval = "30s"
    timeout = "120s"       # or "2m"
    grace_period = "30s"
    method = "GET"
    path = "/health"


[processes]
  app = "gunicorn App:app --bind 0.0.0.0:8080 --workers 1 --timeout 300 --worker-class sync"

# Machine configuration
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1